Mobile and desktop version
sentayhu19/capstone-project pull request #4
Opened 2022-03-10 18:11 UTC by sentayhu19

**in this pull**

- Desktop and Mobile version of the web site
 - Transform added on images 
- Hamburger menus
- about page and index page
- https://www.loom.com/share/b354f51e724c4a41a1df55dd791b525b

2022-03-10 19:00 UTC, Kingstalux requested changes
Hi @sentayhu19 , 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!
![68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f5754646735474252343558364e6278714a4b2f67697068792e676966](https://user-images.githubusercontent.com/85113567/157734900-5fb6e156-994b-45cb-912d-0c53b31440ec.gif)



## Suggested changes
_Check the comments under the review._
- [ ] Your video presentation did not contain your mobile version and a piece of interesting code you had when you worked on this project. Kindly record another video with all the necessary information 😄 
- [ ] Your page breaks at exactly `768px` and your `Start blogging` button is out of place right up to `1140px`. It would be great to implement your mobile version from around `992px` to `1024px` to prevent this kind of behavior. Kindly rectify this issue.
- Your page:
![Annotation 2022-03-10 193033](https://user-images.githubusercontent.com/85113567/157735583-fcb2c016-c39a-4565-94e3-97b8523a78dc.jpg)


 
![Annotation 2022-03-10 193053](https://user-images.githubusercontent.com/85113567/157735552-40cd334a-1b3d-4d3e-b48e-3131d9563961.jpg)

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-03-10 19:00 UTC, Kingstalux commented on about.html
> +          <div>  <img src="./assets/images/Twitter.png" class="social-media-top-item1" alt="twitter" ></div>
- [ ] Great job so far 👍 It would be great to add a white Facebook and Twitter icon so as to follow the design more closely and also remove the extra YouTube icon.
- Your navbar:
![Annotation 2022-03-10 193220](https://user-images.githubusercontent.com/85113567/157732402-2582d89f-212b-4b93-a21c-1fc32ff7a2c1.jpg)
- Required design:
![Annotation 2022-03-10 193243](https://user-images.githubusercontent.com/85113567/157732444-a3f02b0b-df61-40c2-a0c3-6292ea1f0faa.jpg)

2022-03-10 19:00 UTC, Kingstalux commented on about.html
> +<h2 class="about-title">About our Blog web site</h2>
- [ ] Nice design on this page 💯 It would be better to add some more margin to your `About our blog website` section since its too close to the horizontal line just as in the required design
- Your design:
![Annotation 2022-03-10 193340](https://user-images.githubusercontent.com/85113567/157732921-f8cf4962-e313-4856-a5ef-b6f005562982.jpg)
- Required design:

![Annotation 2022-03-10 193413](https://user-images.githubusercontent.com/85113567/157732974-4a57fb77-44d5-40ca-a034-aa8976f6dce7.jpg)

2022-03-10 19:00 UTC, Kingstalux commented on about.html
> +                    </footer>
- [ ] You'll notice that in the mobile version, the bottom of the `About` page contains a partner's section and a white `footer` section. It would be great if you could implement that as well 👍 
- Your design:
![Annotation 2022-03-10 194705](https://user-images.githubusercontent.com/85113567/157733578-d08dabe2-24d4-4580-b2d3-4eccc24452ab.jpg)
- Required design:
![Annotation 2022-03-10 193745](https://user-images.githubusercontent.com/85113567/157733607-27afc874-6a3c-4c87-8a57-aee7959c6902.jpg)

2022-03-10 19:00 UTC, Kingstalux commented on index.html
> +    </section>
- [ ] Good job generating the speaker's section dynamically from JavaScript but you'll notice that in the mobile version, only 2 speakers should be displayed together with a `more` button.  When a user clicks on the `more` button the rest of the speakers will then be displayed. Kindly implement this functionality 👍 
- Required design:
![Annotation 2022-03-10 193647](https://user-images.githubusercontent.com/85113567/157734740-bf4dff79-cf58-4c36-a1b1-53b2e60af664.jpg)

2022-03-11 19:37 UTC, thecodechaser approved these changes
## STATUS: APPROVED 🟢

## Hi @sentayhu19👋, 

### You did a marvelous job on the capstone project and this is one of the best projects I have seen so far!

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️
- Good presentation video. ✔️ 

## Optional suggestions
- [ ]  I am marking these changes as optional because they were missed by the previous reviewer, But I strongly suggest considering them. Please check the comments under the review.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-11 19:37 UTC, thecodechaser commented on about.html
> +            </ul>
- [ ] When I open the mobile menu and switch to the desktop screen the mobile menu is still on the screen it should disappear. Please make sure when we switch the screen from mobile to desktop the mobile menu should disappear.
 - You can use media queries for that if the screen cross the min-width you can set your mobile menu `display: none`

See the image for reference 

![image](https://user-images.githubusercontent.com/83803414/157938553-491d3f46-4be0-4d28-9b88-209a6573cee5.png)

2022-03-11 19:37 UTC, thecodechaser commented on about.html
> +                </div>
- [ ] Please make sure the partner's section is in the center and follow the Behance design

### Your design

![image](https://user-images.githubusercontent.com/83803414/157940293-b47cdb73-8fdd-4a2e-9d24-d2ef748552ce.png)

### Behance design

![image](https://user-images.githubusercontent.com/83803414/157940483-02eb2641-ddbf-4d87-82d4-87ee6c0d2b0c.png)

2022-03-14 14:57 UTC, merged